# peripheral config

CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

#BLE USB settings

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_BT=y



# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=n


# LED indicators
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
