#BLE USB settings

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

CONFIG_ZMK_USB=n
CONFIG_ZMK_BLE=y
CONFIG_BT=y

# LED indicators

CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y


# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=n


# Sleeping configuration
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# EC11
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

